openapi: 3.0.0
info:
  title: Library API
  description: API for managing books in a library.
  version: 1.0.0
servers:
  - url: http://api.library.com/v1
    description: Main production server
paths:
  /books:
    get:
      operationId: getBooks
      summary: Returns a list of books.
      responses:
        '200':
          description: A JSON array of books
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
    post:
      operationId: addBook
      summary: Adds a new book.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the book
                author:
                  type: string
                  description: Author of the book
      responses: 
        '201':
          description: Book successfully added
        '400':
          description: Invalid input
